class ProductItem:
    uuid=""
    id=""
    company =""
    productname =""
    type = ""
    type1 =""
    type2 = ""
    type3 = ""
    type4 = ""
    designtype =""
    productattr =""
    acceptance =""
    period = ""
    paytype =""
    termcode =""
    salestate=""
    stopsaledate =""
    briefurl =""
    detailurl =""
    pdfurl =""


    def __init__(self):
        uuid = ""
        id = ""
        company = ""
        productname = ""
        type =""
        designtype = ""
        productattr = ""
        acceptance = ""
        period = ""
        paytype = ""
        termcode = ""
        salestate = ""
        stopsaledate = ""
        briefurl = ""
        detailurl = ""
        pdfurl = ""
